version: '3.8'

services:
  jms:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka:
    image: mssc-beer-eureka/mssc-brewery-eureka
    ports:
      - "8761:8761"
  config-server:
    image: mssc-beer-config-server/mssc-config-server
    ports:
      - "8888:8889"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
  inventory-service:
     image: mssc-beer-inventory/mssc-beer-inventory-service
     ports:
       - "8082:8082"
     depends_on:
       - eureka
       - config-server
       - jms
     restart: always
     environment:
       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
       SPRING_PROFILES_ACTIVE: test
       MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
       SPRING_ZIPKIN_BASEURL: http://zipkin
       SPRING_ARTEMIS_BROKER_URL: tcp://jms:61616